set "LIBRARY_LIB=%LIBRARY_LIB:\=/%"
set "LIBRARY_INC=%LIBRARY_INC:\=/%"

cmake %CMAKE_ARGS% ^
  -G Ninja ^
  -DCMAKE_BUILD_TYPE=Release ^
  -DCMAKE_INSTALL_PREFIX=%PREFIX% ^
  -DCMAKE_PREFIX_PATH=%PREFIX% ^
  -DBUILD_DOCS=OFF ^
  -DBUILD_MOCK=OFF ^
  -DCMAKE_INSTALL_LIBDIR=%LIBRARY_LIB% ^
  -DCMAKE_INSTALL_INCLUDEDIR=%LIBRARY_INC%

cmake --build . --parallel %CPU_COUNT%
cmake --install .
