{% set name = "dlpack" %}
{% set version = "1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dmlc/dlpack/archive/v{{ version }}.tar.gz
  sha256: 2e3b94b55825c240cc58e6721e15b449978cbae21a2a4caa23058b0157ee2fb3

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja

test:
  commands:
    - test -d ${PREFIX}/include/dlpack  # [unix]
    - test -f ${PREFIX}/include/dlpack/dlpack.h  # [unix]
    - test -d ${PREFIX}/lib/cmake/dlpack  # [unix]
    - if not exist %LIBRARY_INC%/dlpack exit 1  # [win]
    - if not exist %LIBRARY_INC%/dlpack/dlpack.h exit 1  # [win]
    - if not exist %LIBRARY_LIB%/cmake/dlpack exit 1  # [win]

about:
  home: https://github.com/dmlc/dlpack
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: DLPack - Open In Memory Tensor Structure
  description: |
    DLPack is an open in-memory tensor structure to for sharing tensor among frameworks
  dev_url: https://github.com/dmlc/dlpack

extra:
  recipe-maintainers:
    - leofang
    - marcelotrevisani
    - kkraus14
    - jakirkham
